# Common Labels
labels:
  app: "egov-idgen"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-idgen"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_idgen_schema"
    image:
      repository: "egov-idgen-db"

# Container Configs
image:
  repository: "egov-idgen"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-idgen/health"
  readinessProbePath: "/egov-idgen/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
idformat-from-mdms: "false"
autocreate-new-seq: "false"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /egov-idgen
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /egov-idgen
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: IDFORMAT_FROM_MDMS
    value: {{ index .Values "idformat-from-mdms" | quote }}
  - name: AUTOCREATE_NEW_SEQ
    value: {{ index .Values "autocreate-new-seq" | quote }}
  - name: MDMS_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: MDMS_SERVICE_SEARCH_URI
    value: "/mdms-v2/v1/_search"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: REDISSON_REDIS_HOST
    value: 'redis.backbone'
  - name: REDISSON_REDIS_PORT
    value: '6379'
  - name: REDISSON_REDIS_TIMEOUT
    value: '10000'
  - name: REDISSON_REDIS_CONNECTION_POOL_SIZE
    value: '20'
  - name: REDISSON_REDIS_CONNECTION_MIN_IDLE_SIZE
    value: '10'
  - name: REDISSON_REDIS_THREADS
    value: '4'
  - name: REDISSON_REDIS_NETTY_THREADS
    value: '4'
  - name: KAFKA_TOPICS_SAVE_IN_ID_POOL
    value: save-in-id-pool
  - name: KAFKA_TOPICS_UPDATE_ID_POOL_STATUS
    value: update-id-pool-status
  - name: KAFKA_TOPICS_SAVE_IN_DISPATCH_LOG
    value: save-dispatch-id-log
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: ID_POOL_SEQ_CODE
    value: id.pool.number.random
  - name: IDGEN_RANDOM_BUFFER
    value: '5'
  - name: LIMIT_PER_USER
    value: '600'
  - name: IDPOOL_FETCH_LIMIT_FROM_DB
    value: '600'
  - name: MULTI_LOCK_WAIT_TIME
    value: '5'
  - name: MULTI_LOCK_LEASE_TIME
    value: '10'
  - name: ID_POOL_CREATE_MAX_BATCH_SIZE
    value: '10000'
  - name: SPRING_DATA_REDIS_DEFAULT_REPLENISHRATE
    value: '4'
  - name: SPRING_DATA_REDIS_DEFAULT_BURSTCAPACITY
    value: '4'
