apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-read-only
subjects:
- kind: User
  name: eks-readonly
  apiGroup: rbac.authorization.k8s.io

