apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress
  labels:
    release: prometheus
spec:
  jobLabel: nginx-ingress
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 30s

