apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "name" is the name of the ClusterRole
  name: eks-read-only
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

