namespace: playground 

# Common Labels
labels:
  app: "playground"
  group: "playground"

# Container Configs
image:
  pullPolicy: IfNotPresent  
  repository: playground 
  tag: "11.19"
replicas: "1"
